import mongoose from "mongoose";

const ideaSchema = new mongoose.Schema({
    user:{
        type: mongoose.Schema.Types.ObjectId, 
        //This tells Mongoose that the value of "user" will be an ObjectId — the unique identifier automatically generated by MongoDB for each document.
        ref: 'User', // it refers to userschema
        required: true
    },
    title:{
        type: String,
        required: true,
        trim: true
    },
    summary:{
        type: String,
        required: true,
        trim: true
    },
    description:{
        type: String,
        required: true,
        trim: true
    },
    tags:{
        type: [String],
        default: []
    }
}, {timestamps: true}) // it tells where it created At 

const Idea = mongoose.model("Ideas", ideaSchema);  // Browser Collection data fetching from MongoDB with creating of ideaSchema
console.log("🧠 Model collection name:", Idea.collection.name);
export default Idea;